[package]
org = "lakshanweerasinghe"
name = "deployment"
version = "0.1.0"
title = "deployment"

[build-options]
sticky = true
[[tool.openapi]]
id = "WeatherAPI"
targetModule = "WeatherAPI"
filePath = "./resources/weather11.yaml"
